import { expect, it } from "vitest";
import parity from "../../contracts/slayer-parity.json";
import {
  bestPrices,
  calculate,
  petLeveling,
  slayers,
} from "./slayerCalculator";

// Synthetic prices, expected results generated by the original Kotlin calculator.
it.each(parity)(
  "matches MithrilAddons: $slayer tier $tier MF $magicFind meter $meter",
  (test) => {
    const slayer = slayers.find((s) => s.displayName === test.slayer)!;
    const tier = slayer.tiers.find((t) => t.number === test.tier)!;
    const prices = bestPrices(
      tier,
      {
        bazaar: Object.fromEntries(
          Object.entries(test.prices).map(([k, v]) => [
            k,
            { instant: v, offer: v },
          ]),
        ),
        auctions: Object.fromEntries(
          Object.entries(test.prices).map(([k, v]) => [
            k,
            { price: v, source: "BIN", samples: 3, spread: 0 },
          ]),
        ),
        npc: {},
      },
      "instant",
    );
    const result = calculate(
      slayer,
      tier,
      test.magicFind,
      60,
      test.meter,
      prices,
      true,
    );
    result.dropRates.forEach((rate, i) =>
      expect(rate).toBeCloseTo(test.rates[i]!, 11),
    );
    expect(result.gross).toBeCloseTo(test.gross, 6);
    expect(result.fees).toBe(test.fees);
    if (test.comparison) {
      expect(result.comparison?.itemName).toBe(test.comparison.itemName);
      expect(result.comparison?.alwaysSelectedCoinsPerHour).toBeCloseTo(
        test.comparison.alwaysSelectedCoinsPerHour,
        6,
      );
      expect(result.comparison?.fillUnselectedCoinsPerHour).toBeCloseTo(
        test.comparison.fillUnselectedCoinsPerHour,
        6,
      );
    } else expect(result.comparison).toBeNull();
  },
);

it("chooses NPC values over a lower market price and keeps missing prices explicit", () => {
  const tier = slayers[0]!.tiers[1]!;
  const prices = bestPrices(
    tier,
    {
      bazaar: { FOUL_FLESH: { instant: 20000, offer: 30000 } },
      npc: { FOUL_FLESH: 25000 },
      auctions: {},
    },
    "instant",
  );
  expect(prices["Foul Flesh"]).toEqual({ price: 25000, source: "NPC" });
  expect(prices["Revenant Flesh"]).toBeUndefined();
  expect(
    bestPrices(
      tier,
      {
        bazaar: { FOUL_FLESH: { instant: 20000, offer: 30000 } },
        npc: { FOUL_FLESH: 25000 },
        auctions: {},
      },
      "offer",
    )["Foul Flesh"]?.price,
  ).toBe(30000);
});

it("preserves pet XP assumptions, shard bonuses, margins, and zero throughput", () => {
  const tier = slayers[0]!.tiers[0]!;
  const quotes = [
    {
      name: "Synthetic pet",
      rarity: "LEGENDARY",
      startLevel: 1,
      endLevel: 100,
      startPrice: 1e6,
      endPrice: 3e6,
      requiredXp: 1e6,
      samples: 6,
    },
  ];
  const base = petLeveling(tier, 60, quotes, false);
  expect(base.active).toBeCloseTo(150 * 60 * 1.6 * 1.5 * 1.05);
  expect(base.shared).toBeCloseTo(base.active * 0.27);
  expect(base.best).toBeCloseTo((base.active + base.shared) * 2);
  const boosted = petLeveling(tier, 60, quotes, true);
  expect(boosted.active).toBeCloseTo(base.active * 1.1);
  expect(boosted.shared).toBeCloseTo(boosted.active * 0.37);
  expect(petLeveling(tier, 0, quotes, false).best).toBe(0);
});
