import { expect, it } from "vitest";
import parity from "../../contracts/slayer-parity.json";
import {
  bestPrices,
  calculate,
  petLeveling,
  rates,
  amount,
  slayers,
  type Slayer,
} from "./slayerCalculator";

// Synthetic prices, expected results generated by the original Kotlin calculator.
it.each(parity)(
  "matches MithrilAddons: $slayer tier $tier MF $magicFind meter $meter",
  (test) => {
    const slayer = slayers.find((s) => s.displayName === test.slayer)!;
    const tier = slayer.tiers.find((t) => t.number === test.tier)!;
    const prices = bestPrices(
      tier,
      {
        bazaar: Object.fromEntries(
          Object.entries(test.prices).map(([k, v]) => [
            k,
            { instant: v, offer: v },
          ]),
        ),
        auctions: Object.fromEntries(
          Object.entries(test.prices).map(([k, v]) => [
            k,
            { price: v, source: "BIN", samples: 3, spread: 0 },
          ]),
        ),
        npc: {},
      },
      "instant",
    );
    const result = calculate(
      slayer,
      tier,
      test.magicFind,
      60,
      test.comparison?.itemName ?? null,
      prices,
      {
        meterXpMultiplier: 1.1,
      },
    );
    const originalRates = rates(slayer, tier, test.magicFind, test.meter, 1.1);
    originalRates.forEach((rate, i) =>
      expect(rate).toBeCloseTo(test.rates[i]!, 11),
    );
    const originalGross = tier.drops.reduce(
      (sum, drop, i) =>
        sum +
        originalRates[i]! * amount(drop) * 60 * (prices[drop.name]?.price ?? 0),
      0,
    );
    expect(originalGross).toBeCloseTo(test.gross, 6);
    expect(result.fees).toBe(test.fees);
    if (test.comparison) {
      // The original comparison always used the highest-value item. The UI
      // now compares the user's selected item when one is chosen.
      const comparison = result.comparison;
      expect(comparison?.itemName).toBe(test.comparison.itemName);
      expect(comparison?.alwaysSelectedCoinsPerHour).toBeCloseTo(
        test.comparison.alwaysSelectedCoinsPerHour,
        6,
      );
      expect(comparison?.fillUnselectedCoinsPerHour).toBeCloseTo(
        test.comparison.fillUnselectedCoinsPerHour,
        6,
      );
      expect(comparison!.optimizedCoinsPerHour + 1e-6).toBeGreaterThanOrEqual(
        comparison!.alwaysSelectedCoinsPerHour,
      );
      expect(comparison!.optimizedCoinsPerHour + 1e-6).toBeGreaterThanOrEqual(
        comparison!.fillUnselectedCoinsPerHour,
      );
    } else expect(result.comparison).toBeNull();
  },
);

it("chooses NPC values over a lower market price and keeps missing prices explicit", () => {
  const tier = slayers[0]!.tiers[1]!;
  const prices = bestPrices(
    tier,
    {
      bazaar: { FOUL_FLESH: { instant: 20000, offer: 30000 } },
      npc: { FOUL_FLESH: 25000 },
      auctions: {},
    },
    "instant",
  );
  expect(prices["Foul Flesh"]).toEqual({ price: 25000, source: "NPC" });
  expect(prices["Revenant Flesh"]).toBeUndefined();
  expect(
    bestPrices(
      tier,
      {
        bazaar: { FOUL_FLESH: { instant: 20000, offer: 30000 } },
        npc: { FOUL_FLESH: 25000 },
        auctions: {},
      },
      "offer",
    )["Foul Flesh"]?.price,
  ).toBe(30000);
});

it("preserves pet XP assumptions, shard bonuses, margins, and zero throughput", () => {
  const tier = slayers[0]!.tiers[0]!;
  const quotes = [
    {
      name: "Synthetic pet",
      rarity: "LEGENDARY",
      startLevel: 1,
      endLevel: 100,
      startPrice: 1e6,
      endPrice: 3e6,
      requiredXp: 1e6,
      samples: 6,
    },
  ];
  const base = petLeveling(tier, 60, quotes);
  expect(base.active).toBeCloseTo(150 * 60 * 1.6 * 1.5 * 1.05);
  expect(base.shared).toBeCloseTo(base.active * 0.27);
  expect(base.best).toBeCloseTo((base.active + base.shared) * 2);
  const boosted = petLeveling(tier, 60, quotes, { shards: true });
  expect(boosted.active).toBeCloseTo(base.active * 1.1);
  expect(boosted.shared).toBeCloseTo(boosted.active * 0.37);
  expect(petLeveling(tier, 0, quotes).best).toBe(0);
});

it("excludes plain Commons and deducts every Kat cost before ranking", () => {
  const base = {
    name: "Synthetic pet",
    rarity: "LEGENDARY",
    startLevel: 1,
    endLevel: 100,
    startPrice: 1e6,
    endPrice: 10e6,
    requiredXp: 25353230,
    samples: 6,
  };
  const kat = {
    coins: 1e6,
    materials: 1e6,
    flowers: 4,
    flowerCost: 1e6,
    total: 3e6,
  };
  const result = petLeveling(slayers[0]!.tiers[0]!, 60, [
    { ...base, rarity: "COMMON", endPrice: 1e9 },
    { ...base, rarity: "COMMON", kat, startPrice: 1e5 },
    base,
  ]);
  expect(result.pets).toHaveLength(2);
  expect(result.pets[0]!.rarity).toBe("LEGENDARY");
  expect(result.pets[1]!.coinsPerXp).toBeCloseTo(6.9e6 / 25353230);
  expect(result.best).toBeCloseTo((result.profitXp * 9e6) / 25353230);
});

it("applies Aatrox meter XP and quest discounts independently to both strategies", () => {
  const slayer = slayers[0]!;
  const tier = slayer.tiers[4]!;
  const prices = { "Warden Heart": { price: 100000000, source: "BIN" } };
  const run = (options = {}) =>
    calculate(slayer, tier, 200, 60, "Warden Heart", prices, options);
  const base = run();
  const discount = run({ halfPrice: true });
  expect(base.fees).toBe(6000000);
  expect(discount.fees).toBe(3000000);
  expect(discount.dropRates).toEqual(base.dropRates);
  expect(discount.net - base.net).toBeCloseTo(3000000);
  expect(
    discount.comparison!.alwaysSelectedCoinsPerHour -
      base.comparison!.alwaysSelectedCoinsPerHour,
  ).toBeCloseTo(3000000);
  expect(
    discount.comparison!.fillUnselectedCoinsPerHour -
      base.comparison!.fillUnselectedCoinsPerHour,
  ).toBeCloseTo(3000000);
  const xp = run({ meterXpMultiplier: 1.25 });
  expect(xp.fees).toBe(base.fees);
  expect(xp.gross).toBeGreaterThan(base.gross);
  expect(xp.comparison!.fillUnselectedCoinsPerHour).toBeGreaterThan(
    base.comparison!.fillUnselectedCoinsPerHour,
  );
  const both = run({ meterXpMultiplier: 1.25 * 1.1, halfPrice: true });
  expect(both.fees).toBe(discount.fees);
  expect(both.gross).toBeGreaterThan(xp.gross);
  expect(
    calculate(slayer, tier, 200, 0, "Warden Heart", prices, { halfPrice: true })
      .net,
  ).toBe(0);
});

it("keeps Diana perks independent and retains shared XP when excluding the main pet", () => {
  const tier = slayers[0]!.tiers[0]!;
  const quotes = [
    {
      name: "Synthetic pet",
      rarity: "LEGENDARY",
      startLevel: 1,
      endLevel: 100,
      startPrice: 1000000,
      endPrice: 3000000,
      requiredXp: 1000000,
      samples: 6,
    },
  ];
  const base = petLeveling(tier, 60, quotes);
  const slots = petLeveling(tier, 60, quotes, { extraSlots: true });
  expect(slots.active).toBe(base.active);
  expect(slots.slots).toBe(3);
  expect(slots.shared).toBeCloseTo(base.active * 0.37 * 3);
  const xp = petLeveling(tier, 60, quotes, { petXpBoost: true });
  expect(xp.slots).toBe(1);
  expect(xp.active).toBeCloseTo(base.active * 1.35);
  expect(xp.shared).toBeCloseTo(base.shared * 1.35);
  expect(xp.best).toBeCloseTo(base.best * 1.35);
  const sharedOnly = petLeveling(tier, 60, quotes, { excludeActive: true });
  expect(sharedOnly.active).toBe(base.active);
  expect(sharedOnly.shared).toBe(base.shared);
  expect(sharedOnly.profitXp).toBe(base.shared);
  expect(sharedOnly.best).toBeCloseTo(base.shared * 2);
  const all = petLeveling(tier, 60, quotes, {
    shards: true,
    extraSlots: true,
    petXpBoost: true,
    excludeActive: true,
  });
  expect(all.shared).toBeCloseTo(base.active * 1.1 * 1.35 * 0.47 * 3);
  expect(all.best).toBeCloseTo(all.shared * 2);
  expect(all.pets[0]!.coinsPerHour).toBe(all.best);
});

it("finds an interior meter cutoff and uses its expected drops in the profit total", () => {
  const slayer: Slayer = {
    displayName: "Synthetic slayer",
    tiers: [
      {
        number: 3,
        questCost: 10,
        slayerXp: 250,
        spawnCombatXp: 100,
        drops: [
          {
            name: "Synthetic drop",
            bazaarId: null,
            pool: "MAIN",
            weight: 1000,
            minAmount: 1,
            maxAmount: 1,
            auctionName: "Synthetic drop",
            rollsPerBoss: 1,
            separateMagicFindBonus: null,
            npcSellPrice: null,
          },
        ],
      },
    ],
  };
  const tier = slayer.tiers[0]!;
  const prices = { "Synthetic drop": { price: 100, source: "BIN" } };
  const result = calculate(slayer, tier, 0, 60, "Synthetic drop", prices);
  // Exact rational evaluation of the 23 possible cutoffs: eleven selected
  // kills, eleven unselected kills, then the guarantee has the highest rate.
  // 44082693289014908 / 333774599516903313, rounded to a JS number.
  const expectedRate = 0.13207324150135766;
  expect(result.comparison!.requirement).toBe(5500);
  expect(result.comparison!.switchXp).toBe(2750);
  expect(result.dropRates[0]).toBeCloseTo(expectedRate, 12);
  expect(result.gross).toBeCloseTo(expectedRate * 100 * 60);
  expect(result.net).toBeCloseTo(expectedRate * 100 * 60 - 600);
  expect(result.net).toBe(result.comparison!.optimizedCoinsPerHour);
  expect(result.net).toBeGreaterThan(
    result.comparison!.alwaysSelectedCoinsPerHour,
  );
  expect(result.net).toBeGreaterThan(
    result.comparison!.fillUnselectedCoinsPerHour,
  );
  const noMeter = calculate(slayer, tier, 0, 60, null, prices);
  expect(noMeter.dropRates[0]).toBeCloseTo(1 / 11);
  expect(noMeter.comparison!.switchXp).toBe(2750);
  const fastTier = { ...tier, slayerXp: 500 };
  const fast = calculate(
    { ...slayer, tiers: [fastTier] },
    fastTier,
    0,
    60,
    "Synthetic drop",
    prices,
  );
  expect(fast.comparison!.switchXp).toBe(0);
  expect(fast.dropRates[0]).toBeCloseTo(1 / 6);
  const unpriced = calculate(slayer, tier, 0, 60, "Synthetic drop", {});
  expect(unpriced.comparison).toBeNull();
  expect(unpriced.unpriced).toBe(1);
});

it("recommends Spider's more profitable mosquito instead of its more expensive eye", () => {
  const slayer = slayers[1]!;
  const tier = slayer.tiers[4]!;
  const prices = {
    "Digested Mosquito": { price: 33000000, source: "Synthetic" },
    "Primordial Eye": { price: 110000000, source: "Synthetic" },
  };
  const auto = calculate(slayer, tier, 200, 60, null, prices);
  const mosquito = calculate(
    slayer,
    tier,
    200,
    60,
    "Digested Mosquito",
    prices,
  );
  const eye = calculate(slayer, tier, 200, 60, "Primordial Eye", prices);
  expect(mosquito.net).toBeGreaterThan(eye.net);
  expect(auto.comparison!.itemName).toBe("Digested Mosquito");
  expect(auto.comparison!.optimizedCoinsPerHour).toBe(mosquito.net);
  expect(eye.comparison!.itemName).toBe("Primordial Eye");
  expect(
    calculate(slayer, tier, 200, 0, null, prices).comparison!.itemName,
  ).toBe("Digested Mosquito");
  const changed = {
    ...prices,
    "Primordial Eye": { price: 1000000000, source: "Synthetic" },
  };
  expect(
    calculate(slayer, tier, 200, 60, null, changed).comparison!.itemName,
  ).toBe("Primordial Eye");
});
